### ISSUE TITLE
[Bug] Cart is falling through ship

### ISSUE THREAD

**Issue by JohnMetroid** [WhiteSpike/Shopping-Cart#1]
Hey there,

I've been updating my mod pack this morning and I noticed that the cart seems to be falling through the ship.  I didn't catch the exact time this occurred.  It may have been in transition to orbit, or it may have been when saving/reloading into a lobby.  I don't see anything relevant in the log, but I will update this ticket if anything else materializes.

Thanks again for your work on LGU and these items, they're some of the most fun parts of Lethal :)

![image](https://github.com/user-attachments/assets/4f4e07d2-bec8-451b-8cb9-3b25101bcf65)

**Comment by WhiteSpike** [comment]
I can't seem to replicate this behaviour. Wherever I drop the cart, it stays above the surface.

The only thing I can think of is the vanilla bug where it allows drop items below the floor if looking right (thus why it doesn't allow you to crouch as it is very easy to do so with this one).

Coming back to save boot also has the cart above the surface so I'm not sure what's going on. 🤔

**Comment by JohnMetroid** [comment]
I've been playing for the last ~2 hours with a shopping cart and it hasn't dropped into the ship again.  I think it originally occurred from a lobby save/reload.  If I get any more information I'll update you

Thanks for looking into it

**Comment by JohnMetroid** [comment]
closed under the assumption that it occurred from a lobby reload, which seems to be vanilla behavior
